build:
  tests:
    override:
      - command: vendor/bin/phpunit
        coverage:
          file: /tmp/coverage.xml
          format: clover

  nodes:
    tests-php73:
      environment:
        php: 7.3

    tests-php74:
      environment:
        php: 7.4

    tests-php80:
      environment:
        php: 8.0.0

    analysis:
      tests:
        override:
          - php-scrutinizer-run

filter:
  excluded_paths:
    - "tests/"
    - "storage/"